const q=require('lodash');
const a=require('./calc.js');
let p=a.add(20,10);
let y=a.subtract(20,10);
let s=a.multiply(2,2);
let r=a.divide(20,10);
let f=a.modulus(20,15);
console.log(p);
console.log(y);
console.log(s);
console.log(r);
console.log(f);
